/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

import {v4 as uuid} from 'uuid';
import { channelimg1, channelimg2, channelimg3, channelimg4, channelimg5, channelimg6, channelimg7, channelimg8, channelimg9, songimg1, songimg10, songimg11, songimg12, songimg13, songimg14, songimg15, songimg16, songimg17, songimg18, songimg19, songimg2, songimg3, songimg4, songimg5, songimg6, songimg7, songimg8, songimg9 } from '../../asset';

export const videos = [
  {
    _id: uuid(),
    thumbnail: songimg1,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: `${164630792} views`,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg1,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg2,
    title: "Tich Button | Chahida kuch vi nai Punjabi Song - Simar Sethi | New Punjabi Song 2021 | New Song 2022   ",
    description: `Mainu so hai tere ne kade ni bhulungi mukh tera female version .... Presenting the soulful cover version by, Sakhiyaan fame Simar Sethi, of Punjabi love song "Tich Button" originally sung by Kulwinder Billa in punjabi comedy movie Parahune featuring Wamiqa Gabbi, Karamjit Anmol, Harby Sangha and others.`,
    creator: "SagaHits ", 
    views: `${21675591} views`,
    createdAt: "Oct 22, 2021",
    channel_pic: channelimg2,
    video: "h8L2JfZuIxE",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg3,
    title: "Chaand Baaliyan – Aditya A. | Trending Song 2022 | Official Video",
    description: `Presenting the official video of the viral track – Chaand Baaliyan created by Aditya A. Watch the video and create your #ChaandBaaliyan moment now!`,
    creator: "Sony Music India", 
    views: `${24710773} views`,
    createdAt: "Mar 1, 2022",
    channel_pic: channelimg3,
    video: "7c3-Gei5j4w",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg4,
    title: "Chura Liya (Video) | Sachet - Parampara | Himansh K, Anushka S | Irshad K | Ashish P | Bhushan Kumar",
    description: `Gulshan Kumar & T-Series presents Bhushan Kumar's “Chura Liya”. 
    Sachet Tandon and Parampara Tandon’s new romantic track “Chura Liya”. featuring Himansh Kohli & Anushka Sen in the video. The music by Sachet-Parampara and lyrics are by Irshad Kamil. The video is directed by Ashish Panda Enjoy & Stay connected. Hit 'LIKE' if you ♥ this song`,
    creator: "T-Series", 
    views: `${73878869} views`,
    createdAt: "Oct 12, 2021",
    channel_pic: channelimg4,
    video: "Gf0oGsA7DSE",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg5,
    title: "Coke Studio Season 9| Afreen Afreen| Rahat Fateh Ali Khan & Momina Mustehsan",
    description: `Nusrat Fateh Ali Khan was one of the shining lights of Pakistan, a Qawwali Shahehshah whose talent was heralded both locally and globally. To celebrate the legend that still lives 19 years on, Coke Studio presents
    Afreen Afreen, Rahat Fateh Ali Khan & Momina Mustehsan, Episode 2, Coke Studio 9 `,
    creator: "Coke Studio", 
    views: `${359613070 } views`,
    createdAt: " Aug 19, 2016",
    channel_pic: channelimg1,
    video: "kw4tT7SCmaY",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg6,
    title: "Shikayat | Full Music Video | Gangubai Kathiawadi | Alia Bhatt | Sanjay Leela Bhansali |Archana Gore",
    description: `Shikayat, the lyrically and musically rich Qawali from the movie Gangubai Kathiawadi is now out with it's full music video.`,
    creator: "Saregama Music", 
    views:`${4449045} views`,
    createdAt: "Apr 19, 2022",
    channel_pic: channelimg5,
    video: "G-VGi8FodFs",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg7,
    title: "Gangubai Kathiawadi | Jab Saiyaan | Sanjay Leela Bhansali | Alia Bhatt | Shreya Ghoshal | Shantanu M",
    description: `All cards on the table or cards up your sleeve. What does this game of love have in store for Gangubai? "Jab Saiyaan" composed by Sanjay Leela Bhansali, sung by Shreya Ghoshal and penned by A.M Turaz will take you on a journey filled with love and a lot more. Watch this romantic music video portraying a sizzling, mischievous and mysterious chemistry between Alia Bhatt and Shantanu Maheshwari.
    Sanjay Leela Bhansali introduces Shantanu Maheshwari in the world of movies !`,
    creator: "Saregama Music", 
    views: `${63646745} views`,
    createdAt: "Feb 15, 2022",
    channel_pic: channelimg5,
    video: "jJLP6P5QaGs",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg8,
    title: "Kaise Hua |Vishal Mishra |Live | TKSS",
    description: `Kaise Hua Live At TKSS , thank you for all the love that you have given to Kaise Hua and all my music .This one is my dedication to all of you. Be safe , Be Home & Be Healthy. Loads Of Love :)`,
    creator: "Vishal Mishra", 
    views: `${23367151} views`,
    createdAt: "Mar 26, 2020",
    channel_pic: channelimg6,
    video: "qN5OXhQ_UWs",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg9,
    title: "Maiyya Mainu - Jersey | Shahid Kapoor, Mrunal T| Sachet-Parampara,Shellee| Gowtam T| 22nd April 2022",
    description: `Song: Maiyya Mainu
    Music Composed, Arranged and Produced by: Sachet-Parampara`,
    creator: "Zee Music Company", 
    views: `${47207087} views`,
    createdAt: "Dec 29, 2021",
    channel_pic: channelimg7,
    video: "y7MW7d8fb1Y",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg10,
    title: "Thoda Thoda Pyaar | Sidharth Malhotra,Neha Sharma|Stebin Ben,Nilesh Ahuja,Kumaar|Zee Music Originals",
    description: `Producer: Anurag Bedi – Chief Business Officer, Zee Music Company , Song - Thoda Thoda Pyaar , Singer - Stebin Ben`,
    creator: "Zee Music Company", 
    views: `${414819448} views`,
    createdAt: " Feb 12, 2021",
    channel_pic: channelimg7,
    video: "USccSZnS8MQ",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg11,
    title: "Dil Ko Karaar Aaya - Sidharth Shukla & Neha Sharma | Neha Kakkar & YasserDesai | Rajat Nagpal | Rana",
    description: `Anshul Garg presents ‘Dil Ko Karaar Aaya’ ft. Sidharth Shukla & Neha Sharma. Beautifully sung by Neha Kakkar & Yasser Desai.`,
    creator: "Desi Music Factory", 
    views: `${244311483} views`,
    createdAt: "Jul 31, 2020",
    channel_pic: channelimg8,
    video: "lX3vT_Gm_HE",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg12,
    title: "Jug Jug Jeeve (Full Video) | Shiddat | Diana P, Mohit R | Sachet T Parampara T| Sachin - Jigar",
    description: `Presenting the full video of the song "Jug Jug Jeeve" from the movie #Shiddat. 
    This song is sung by Sachet Tandon, Parampara Tandon & Sachin - Jigar, music by Gourov Dasgupta, and the lyrics are penned by Kunwar Juneja.
    
    Gulshan Kumar & Prem Vijan presents Dinesh Vijan's A Maddock Original Film  A Shiddat Films UK Production. The movie is featuring Sunny Kaushal, Radhika Madan, Mohit Raina & Diana Penty. It is produced by Dinesh Vijan, Bhushan Kumar, and Firuzi Khan. The film is directed by Kunal Deshmukh.
    
    Feel the power of love with shiddat wala pyaar.`,
    creator: "T-Series", 
    views: `${73422132} views`,
    createdAt: "Oct 18, 2021",
    channel_pic: channelimg4,
    video: "Irw8llgSC3s",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg13,
    title: "Pyaar Ho Jayega (Official Video) Vishal Mishra | Tunisha Sharma | Akshay Tripathi | VYRL Originals",
    description: `VYRL Originals present a classic romantic melody ‘Pyaar Ho Jayega’ by Vishal Mishra. The music video stars Vishal Mishra himself alongside the beautiful Tunisha Sharma, who is popularly known to play the new lead actress of the show Hero – Gayab Mode On. Pyaar Ho Jayega has an evolved sound with a tinge of 90’s style rhythm, and the song has been composed by Vishal Mishra and co-written by him and Akshay Tripathi. Directed by Ray Haan Patni the music video narrates a cute story where Vishal who portrays a singer is seen struck by love at first sight with his video director Tunisha on the sets of a shoot. The innocent chemistry between them undoubtedly creates an ambiance of magic.`,
    creator: "VYRLOriginals", 
    views: `${14300138} views`,
    createdAt: " Sep 15, 2021",
    channel_pic: channelimg9,
    video: "dZTC6YcEAJE",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg14,
    title: "Video: Mast Nazron Se | Rochak K ft Jubin Nautiyal, Nikita Dutta | Manoj M | Ashish P | Bhushan K",
    description: `Presenting #MastNazronSe Song by #JubinNautiyal
    Gulshan Kumar & TSeries peresents Bhushan Kumar's 'Mast Nazron Se' featuring Jubin Nautiyal & Nikita Dutta Feat. Himansh Kohli and Anushka Sen. Sung by Jubin Nautiyal, composed by Rochak Kohli, lyrics are penned by Manoj Muntashir and directed by Ashish Panda. Also featuring Himansh Kohli & Anushka Sen.`,
    creator: "T-Series ", 
    views: `${88373119} views`,
    createdAt: "Mar 31, 2022",
    channel_pic: channelimg4,
    video: "Tc8kb5HBNrA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg15,
    title: "Tu Bhi Sataya Jayega (Official Video) Vishal Mishra | Aly Goni, Jasmin Bhasin | VYRL Originals",
    description: `VYRL Originals presents the multi award-winning singer-composer Vishal Mishra’s Tu Bhi Sataya Jayega featuring Bigg Boss fame and popular couple Aly Goni and Jasmin Bhasin. The song has been written by Vishal Mishra and Kaushal Kishore narrating this story from a female perspective. The Music Video has been directed by Navjit Buttar and has been shot in a grand scale. Watch Aly & Jasmin in a never before seen avatar, showcasing skilfully the pain and anguish of a toxic relationship. You are in for a surprise as the story unfolds to a shocking end.`,
    creator: "VYRLOriginals", 
    views: `${114879628} views`,
    createdAt: "Apr 27, 2021",
    channel_pic: channelimg9,
    video: "eY3m3ji1q84",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg16,
    title: "Aaj Bhi (Official Video) - Vishal Mishra | Ali Fazal, Surbhi Jyoti | VYRLOriginals",
    description: `VYRL Originals presents Vishal Mishra’s Aaj Bhi. A soulful musical journey dedicated to that special someone! Ali Fazal (of Mirzapur fame) and Surbhi Jyoti (of Naagin fame) beautifully showcase & bring alive this story in a video directed by Gurmmeet Singh.`,
    creator: "VYRLOriginals", 
    views: `${107678863} views`,
    createdAt: "Apr 9, 2020",
    channel_pic: channelimg9,
    video: "K0ibsAQTyRQ",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg17,
    title: "Channa Mereya Full Video - ADHM|Ranbir Kapoor, Anushka|Arijit Singh|Pritam|Karan Johar",
    description: `Channa Mereya is soul of Ae Dil Hai Mushkil music album.
    Here is the full video of Karan Johar's favorite song in the album, the lyrics are given by Amitabh Bhattacharya, music by Pritam and sung by Arijit Singh`,
    creator: "SonyMusicIndiaVEVO", 
    views: `${177198311} views`,
    createdAt: "Sep 4, 2017",
    channel_pic: channelimg3,
    video: "284Ov7ysmfA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg18,
    title: "Tumse Pyaar Karke (Video) Tulsi Kumar, Jubin N, Gurmeet C, Ihana D, Payal, Kunaal, Navjit, Bhushan K",
    description: `Gulshan Kumar & T-Series presents 'Tumse Pyaar karke' sung by Tulsi Kumar & Jubin Nautiyal featuring Gurmeet Choudhary & Ihana Dhillon in a beautiful story. 

    We hope you enjoy the song! `,
    creator: "T-Series", 
    views: `${64350569} views`,
    createdAt: "Feb 1, 2022",
    channel_pic: channelimg4,
    video: "LZ-Qn4q3sbU",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg19,
    title: "Kuch Baatein Song | Payal Dev, Jubin Nautiyal | Kunaal Vermaa | Ashish Panda | Gurmeet C, Bhushan K",
    description: `Presenting #KuchBaatein song.
    Gulshan Kumar & T-Series presents Bhushan Kumar's "Kuch Baatein" featuring Gurmeet Choudhary, Payal Dev, Musskan Sethi & Sana Khan, sung by Payal Dev & Jubin Nautiyal, composed by Payal Dev and lyrics are penned by Kunaal Verma.`,
    creator: "T-Series", 
    views: `${41038462} views`,
    createdAt: "Mar 10, 2022",
    channel_pic: channelimg4,
    video: "3fpP2dM02tM",
    categoryName: "song",
  },
];
