/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

import {v4 as uuid} from 'uuid';
import { channelimg1, channelimg2, channelimg3, channelimg4, channelimg5, channelimg6, channelimg7, channelimg8, channelimg9, songimg1, songimg10, songimg11, songimg12, songimg13, songimg14, songimg15, songimg16, songimg17, songimg18, songimg19, songimg2, songimg3, songimg4, songimg5, songimg6, songimg7, songimg8, songimg9 } from '../../asset';

export const videos = [
  {
    _id: uuid(),
    thumbnail: songimg1,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg1,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg2,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg2,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg3,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg3,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg4,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg4,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg5,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg4,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg6,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg5,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg7,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg5,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg8,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg6,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg9,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg7,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg10,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg7,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg11,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg8,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg12,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg4,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg13,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg9,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg14,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg4,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg15,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg9,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg16,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg9,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg17,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg3,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg18,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg4,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },
  {
    _id: uuid(),
    thumbnail: songimg19,
    title: "Coke Studio | Season 14 | Pasoori | Ali Sethi x Shae Gill",
    description: `Let’s transcend boundaries and bridge distances through compassion, love and identity. 
    `,
    creator: "Coke Studio", 
    views: 126084390,
    createdAt: " 07th FEB 2022",
    channel_pic: channelimg4,
    video: "5Eqb_-j3FDA",
    categoryName: "song",
  },


];
